package ChatApp;

/**
* ChatApp/ServerInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MyInterfaces.idl
* jueves 10 de marzo de 2022 11H18' CET
*/

public final class ServerInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public ChatApp.ServerInterface value = null;

  public ServerInterfaceHolder ()
  {
  }

  public ServerInterfaceHolder (ChatApp.ServerInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ChatApp.ServerInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ChatApp.ServerInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ChatApp.ServerInterfaceHelper.type ();
  }

}
