package ChatApp;


/**
* ChatApp/ServerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MyInterfaces.idl
* jueves 10 de marzo de 2022 11H18' CET
*/

public interface ServerInterface extends ServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerInterface
