package ChatApp;


/**
* ChatApp/ServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MyInterfaces.idl
* jueves 10 de marzo de 2022 11H18' CET
*/

public interface ServerInterfaceOperations 
{
  String connection (String userName);
  void newMessages (String roomName, String message);
  String getMessages (String roomName);
  String listUsers (String roomName);
  String listRooms ();
  String createNewRooms (String roomName);
  String joinRoom (String roomToJoin, String name);
  String leaveRoom (String roomToLeave, String name);
  void disconnect (String userName, String roomName);
} // interface ServerInterfaceOperations
